#**Import pandas**

In [ ]:
import pandas as pd

#**Openeing a local csv file from own laptop**

In [ ]:
df=pd.read_csv('/content/placement.csv')

In [ ]:
df.head()

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

#**Opening a csv file from an URL**

In [ ]:
import requests
from io import StringIO
url ="https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv: 66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)
pd.read_csv(data)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

#**Sep parameter**
##used to tell that how our data is separated by.
##eg: csv(comma separted),tsv(tap separated)

In [ ]:
pd.read_csv('/content/titanic.tsv')

,1\t0\t3\tBraund,Mr. Owen Harris\tmale\t22\t1\t0\tA/5 21171\t7.25\t\N\tS
0,2\t1\t1\tCumings,Mrs. John Bradley (Florence Briggs Thayer)\tf...
1,3\t1\t3\tHeikkinen,Miss. Laina\tfemale\t26\t0\t0\tSTON/O2. 31012...
2,4\t1\t1\tFutrelle,Mrs. Jacques Heath (Lily May Peel)\tfemale\t3...
3,5\t0\t3\tAllen,Mr. William Henry\tmale\t35\t0\t0\t373450\t8....
4,6\t0\t3\tMoran,Mr. James\tmale\t\N\t0\t0\t330877\t8.4583\t\N\tQ
...,...,...
885,887\t0\t2\tMontvila,Rev. Juozas\tmale\t27\t0\t0\t211536\t13\t\N\tS
886,888\t1\t1\tGraham,Miss. Margaret Edith\tfemale\t19\t0\t0\t11205...
887,889\t0\t3\tJohnston,"Miss. Catherine Helen ""Carrie""\tfemale\t\N\t1..."
888,890\t1\t1\tBehr,Mr. Karl Howell\tmale\t26\t0\t0\t111369\t30\t...
889,891\t0\t3\tDooley,Mr. Patrick\tmale\t32\t0\t0\t370376\t7.75\t\N\tQ

In [ ]:
pd.read_csv('/content/titanic.tsv',sep='\t',names=['PassengerId','Survived','Pclass','Name','Sex','Age','SibSp','Parch','Ticket','Fare','Cabin','Embarked'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,\N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,\N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,\N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,\N,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,\N,1,2,W./C. 6607,23.4500,\N,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,\N,Q

#**Index_col parameter**
# remove google collab index with your index which is present in dataset

In [ ]:
pd.read_csv('/content/titanic.tsv',sep='\t',names=['PassengerId','Survived','Pclass','Name','Sex','Age','SibSp','Parch','Ticket','Fare','Cabin','Embarked'],index_col='PassengerId')

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,\N,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,\N,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,\N,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,\N,S
888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,\N,1,2,W./C. 6607,23.4500,\N,S
890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,\N,Q

##**use_cols parameter**
## if we want to use only few cols from dataset

In [ ]:
pd.read_csv('/content/placement.csv')

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [ ]:
pd.read_csv('/content/placement.csv',usecols=['cgpa','iq','placement'])

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

#**skiprows/nrows parameter**

In [ ]:
pd.read_csv('/content/placement.csv',skiprows=[0,1])

     1  5.9  106.0  0
0    2  5.3  121.0  0
1    3  7.4  132.0  1
2    4  5.8  142.0  0
3    5  7.1   48.0  1
4    6  5.7  143.0  0
..  ..  ...    ... ..
93  95  4.3  200.0  0
94  96  4.4   42.0  0
95  97  6.7  182.0  1
96  98  6.3  103.0  1
97  99  6.2  113.0  1

[98 rows x 4 columns]

#**loading a huge dataset in chunks**

In [ ]:
dfs=pd.read_csv('/content/placement.csv',chunksize=20)

In [ ]:
for chunks in dfs:
   print(chunks.shape)

(20, 4)
(20, 4)
(20, 4)
(20, 4)
(20, 4)